apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xi0g6ai3b-java-springboot
  janus-idp.io/tekton: xi0g6ai3b-java-springboot
  backstage.io/kubernetes-id: xi0g6ai3b-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xi0g6ai3b-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
